packages:
  - packages/**
  - playground/**
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - lmdb
  - msgpackr-extract
  - rolldown
  - sharp
  - unrs-resolver
