packages:
  - packages/**
  - playground/**
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - rolldown
ignoredBuiltDependencies:
  - protobufjs
  - lmdb
  - msgpackr-extract
  - sharp
