name: Build packages

on: [ push, pull_request ]

jobs:
  build:
    name: Build packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Enable corepack
        run: corepack enable

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          check-latest: true
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build all packages
        run: pnpm run build

      - name: Run all tests
        run: pnpm run test
      
      - name: Release preview
        # Only run on pull requests
        if: github.event_name == 'pull_request'
        run: pnpx pkg-pr-new publish --compact --comment=update './packages/sonda' './packages/unplugin-sourcemaps'
