name: Build packages

on: [ push, pull_request ]

jobs:
  build:
    name: Build packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run all tests
        run: pnpm run test

      - name: Build all packages
        run: pnpm run build
      
      - name: Release preview
        run: pnpx pkg-pr-new publish --compact --comment=update './packages/sonda' './packages/unplugin-sourcemaps'
